// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-hackernews/client (interfaces: Scraper)

// Package mocks is a generated GoMock package.
package mocks

import (
	feed "github.com/go-hackernews/client/feed"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockScraper is a mock of Scraper interface
type MockScraper struct {
	ctrl     *gomock.Controller
	recorder *MockScraperMockRecorder
}

// MockScraperMockRecorder is the mock recorder for MockScraper
type MockScraperMockRecorder struct {
	mock *MockScraper
}

// NewMockScraper creates a new mock instance
func NewMockScraper(ctrl *gomock.Controller) *MockScraper {
	mock := &MockScraper{ctrl: ctrl}
	mock.recorder = &MockScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScraper) EXPECT() *MockScraperMockRecorder {
	return m.recorder
}

// ScrapeHNFeed mocks base method
func (m *MockScraper) ScrapeHNFeed(arg0 int) (*[]feed.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrapeHNFeed", arg0)
	ret0, _ := ret[0].(*[]feed.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScrapeHNFeed indicates an expected call of ScrapeHNFeed
func (mr *MockScraperMockRecorder) ScrapeHNFeed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrapeHNFeed", reflect.TypeOf((*MockScraper)(nil).ScrapeHNFeed), arg0)
}
