package settings

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/bensadeh/circumflex/categories"
)

// FileConfig holds the raw contents of config.toml. Nil pointer fields (and
// a nil WideView) mean the key was absent from the file, which lets callers
// distinguish "not set" from an explicit value.
type FileConfig struct {
	CommentWidth *int     `toml:"comment_width"`
	ArticleWidth *int     `toml:"article_width"`
	Indent       *int     `toml:"indent"`
	History      *bool    `toml:"history"`
	NerdFonts    *bool    `toml:"nerdfonts"`
	Images       *bool    `toml:"images"`
	Categories   []string `toml:"categories"`
	Pages        *int     `toml:"pages"`
	WideView     any      `toml:"wide_view"`
}

func LoadConfig(path string) (*FileConfig, error) {
	cfg := &FileConfig{}

	if _, statErr := os.Stat(path); os.IsNotExist(statErr) {
		return cfg, nil
	}

	md, err := toml.DecodeFile(path, cfg)
	if err != nil {
		return nil, err
	}

	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		keys := make([]string, len(undecoded))
		for i, key := range undecoded {
			keys[i] = key.String()
		}

		return nil, fmt.Errorf("unknown keys in %s: %s", path, strings.Join(keys, ", "))
	}

	return cfg, nil
}

// Apply overlays the values set in the file onto c, clamping them the same
// way the corresponding flags do.
func (f *FileConfig) Apply(c *Config) error {
	if f.CommentWidth != nil {
		c.CommentWidth = ClampWidth(*f.CommentWidth)
	}

	if f.ArticleWidth != nil {
		c.ArticleWidth = ClampWidth(*f.ArticleWidth)
	}

	if f.Indent != nil {
		c.Indent = ClampIndent(*f.Indent)
	}

	if f.History != nil {
		c.DoNotMarkSubmissionsAsRead = !*f.History
	}

	if f.NerdFonts != nil {
		c.EnableNerdFonts = *f.NerdFonts
	}

	if f.Images != nil {
		c.EnableImages = *f.Images
	}

	if len(f.Categories) > 0 {
		c.Categories = strings.Join(f.Categories, ",")
	}

	if f.Pages != nil {
		c.PageMultiplier = ClampPageMultiplier(*f.Pages)
	}

	return f.applyWideView(c)
}

func (f *FileConfig) applyWideView(c *Config) error {
	switch value := f.WideView.(type) {
	case nil:
		return nil
	case int64:
		if value < 1 {
			return fmt.Errorf("wide_view: must be at least 1, got %d", value)
		}

		c.WideViewMinWidth = int(value)

		return nil
	case string:
		width, err := ParseWideView(value)
		if err != nil {
			return fmt.Errorf("wide_view: %w", err)
		}

		c.WideViewMinWidth = width

		return nil
	default:
		return fmt.Errorf(`wide_view: must be "always", "never" or a column count`)
	}
}

func configHeader() string {
	return "# circumflex configuration\n" +
		"#\n" +
		"# All keys are optional; omitted keys keep their defaults.\n" +
		"# Command-line flags override values set here.\n\n"
}

func exampleConfigHeader() string {
	return "# circumflex configuration\n" +
		"#\n" +
		"# Copy this file to your config directory as config.toml, or run\n" +
		"# `clx default-config` to write it there for you.\n" +
		"# All keys are optional; omitted keys keep their defaults.\n" +
		"# Command-line flags override values set here.\n\n"
}

// defaultConfigBody lists every key commented out with its default value.
// Setting keys are commented as "#key = value" (no space) so tests can tell
// them apart from prose comments and verify they parse.
func defaultConfigBody() string {
	names := strings.Split(categories.Default, ",")
	for i, name := range names {
		names[i] = fmt.Sprintf("%q", name)
	}

	return fmt.Sprintf(`# Width of the comment section in columns.
#comment_width = %d

# Width of articles in Reader Mode in columns.
#article_width = %d

# Spaces of indentation per comment depth level.
#indent = %d

# Mark stories as read when opened.
#history = true

# Use Nerd Fonts icons (requires a Nerd Font-patched font).
# Defaults to on in Ghostty, off elsewhere.
#nerdfonts = true

# Show article images in Reader Mode.
# Requires a terminal with Kitty graphics support (Ghostty, Kitty, Konsole).
#images = false

# Categories shown in the header, in order.
# Available: %s
#categories = [%s]

# Pages to fetch per category (1-5).
#pages = %d

# Show stories in a pane next to the front page: "always", "never",
# or the minimum terminal width in columns.
#wide_view = %d
`,
		defaultCommentWidth, defaultArticleWidth, defaultIndent,
		strings.Join(categories.AvailableNames(), ", "), strings.Join(names, ", "),
		defaultPageMultiplier, DefaultWideViewMinWidth)
}

// ExampleConfig renders the annotated default config shipped as
// config.toml.example; regenerated by share/generate_all.sh.
func ExampleConfig() []byte {
	return []byte(exampleConfigHeader() + defaultConfigBody())
}

func WriteDefaultConfig(path string) error {
	if _, statErr := os.Stat(path); statErr == nil {
		return fmt.Errorf("config already exists at %s", path)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	return os.WriteFile(path, []byte(configHeader()+defaultConfigBody()), 0o600)
}
