= clx(1)
:doctype: manpage
:manmanual: circumflex
:man source: circumflex {release-version}
:revdate: {docdate}

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]


== Name

clx - it's Hacker News in your terminal

== Synopsis

*clx* [_OPTION_]...

== Description

*circumflex* lets you browse Hacker News in your terminal.
Quickly and easily visit the comment section or read the article in Reader Mode.

== Keybindings

_Enter_::
Read the comment section.

_Space_::
Read the article in Reader Mode.

_r_::
Re-fetches submissions for current category.
Purges already fetched submissions from other categories.

_Tab_::
Change category (use Shift + Tab to change in opposite direction).

_o_::
Open link to article in browser.

_c_::
Open comment section in browser.

_f_, _V_::
Add currently highlighted submission to favorites.

_x_::
Remove currently highlighted submission from favorites.

_u_::
Toggle read/unread for the currently highlighted submission.

_g_, _G_::
Go to the top/bottom of the list.

_i_, _?_::
Bring up the help screen.

_q_::
Quit to prompt.

== Comment Section

The comment section has two interaction modes, toggled with _Tab_.

=== Read Mode

The default mode. Scroll through the comment section line by line.

_j_, _k_::
Scroll down/up one line.

_d_, _u_::
Scroll down/up half a page.

_Space_/_f_, _b_::
Page down/up.

_g_, _G_::
Go to top/bottom.

_n_, _N_::
Jump to next/previous top-level comment.

_h_, _l_::
Collapse/expand one level.

_Enter_::
Toggle collapse all.

_Tab_::
Switch to navigate mode.

_i_, _?_::
Bring up the help screen.

_q_, _Esc_::
Go back.

=== Navigate Mode

Jump between individual comments instead of scrolling line by line.

_j_, _k_::
Next/previous comment.

_d_, _u_::
Scroll down/up half a page.

_n_, _N_::
Jump to next/previous top-level comment.

_h_, _l_::
Collapse/expand current comment.

_Enter_::
Toggle collapse for current comment.

_Tab_::
Switch to read mode.

_i_, _?_::
Bring up the help screen.

_q_, _Esc_::
Go back.

== Reader Mode

_j_, _k_::
Scroll down/up one line.

_d_, _u_::
Scroll down/up half a page.

_Space_/_f_, _b_::
Page down/up.

_g_, _G_::
Go to top/bottom.

_n_, _N_::
Jump to next/previous section.

_i_, _?_::
Bring up the help screen.

_q_, _Esc_::
Go back.

== Commands

*clx add* [_ID_]::
Add item to list of favorites by _ID_.

*clx article* [_ID_]::
Go directly to Reader Mode for a given item _ID_ without first going through the main view.

*clx comments* [_ID_]::
Go directly to the comment section for a given item _ID_ without first going through the main view.

*clx url* [_URL_]::
Open a URL directly in Reader Mode

*clx clear*::
Clear the history of visited items.

*clx version*::
Print the version number of *circumflex*.

*clx default-theme*::
Write default theme config to the config directory.

== Options

*-c* _n_, *--comment-width*=_n_::
Set the comment width to _n_ columns.

*-d, --disable-history*::
Disable marking stories as read.

*-a* _n_, *--article-width*=_n_::
Set the article width in Reader Mode to _n_ columns.

*-n, --nerdfonts*::
Enable Nerd Fonts icons as decorators for some elements (requires a Nerd Font-patched font).
Auto-enabled for Ghostty, which embeds Nerd Fonts.

*-v, --version*::
Show the current version of *circumflex*.

*--categories*::
Set the categories in the header. Available categories: top, new, best, ask, show.
First category will be treated as the default one. Separate categories with comma.
Default value: "top,best,ask,show"

*--pages*=_n_::
Set the number of pages to fetch per category, between 1 and 5.
Higher values fetch more stories but increase load time.
Only applies to top, new and best. Ask and show always fetch one page because their
story pools are small (~150-200 stories).
Default: 3.

== History

*circumflex* tracks which stories you have visited.
Visited stories are dimmed in the list. When returning to a comment section, comments posted since
your last visit are highlighted with a new-comment indicator.

History is stored as a JSON file in the OS cache directory.
Use *clx clear* to reset it, or *--disable-history* to turn tracking off entirely.

== Favorites

Press _f_ to add the currently highlighted submission to your list of favorites.
Remove submissions from the Favorites page with _x_.

Favorites are stored as a pretty-printed JSON file in the OS config directory,
making them both human-readable and VCS-friendly.

== Environment Variables

*CLX_BROWSER*::
Set to a custom command to be run when opening links. The URL to the website will be appended to
CLX_BROWSER and ran as a single command.

== See also

*vim*(1)

== About

Ben Sadeh (github.com/bensadeh/circumflex)

Released under the MIT License

