= clx(1)
:doctype: manpage
:manmanual: circumflex
//:mansource: clx
:release-version: 2.2
//:man version:  {revnumber}
:man source: circumflex {release-version}

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]


== Name

clx - it's Hacker News in your terminal

== Synopsis

*clx* [_OPTION_]...

== Description

*clx* lets you browse Hacker News from the comfort of your own terminal. Visit the comment section or read the article
in Reader Mode.

== Keybindings

_Enter_::
  Read the Comment section

_Space_::
  Read the article in Reader Mode

_r_::
  Refresh

_Tab_::
  Change category

_o_::
  Open link to article in browser

_c_::
  Open comment section in browser

_f_::
  Add to favorites

_x_::
  Remove from favorites

_q_::
  Quit

== Navigation
*clx* pipes all its content to the pager *less*. To enjoy and use clx effectively, it is recommended to use the following keybindings for moving around:

_j_, _k_::
  Scroll up/down one line

_d_, _u_::
  Scroll up/down one half-page

_n_, _N_::
  Scroll between the next/previous _top-level_ comment (comment section) or _headline_ (Reader Mode)

== Commands

*clx add* [_ID_]::
  Add item to list of favorites by _ID_. Enter the comment section from inside *clx* to update fields.

*clx view* [_ID_]::
  Directly go to the comment section for a given item _ID_ without going through the main view.

*clx clear*::
  Clear the history of visited __ID__s from ~/.cache/circumflex/history.json.

== Options

*-c* _n_, *--comment-width*=_n_::
  Set the comment width to _n_ columns.

*-p, --plain-headlines*::
  Disable syntax highlighting for headlines.

*-o, --plain-comments*::
  Disable syntax highlighting for comments.

*-s, --disable-emojis*::
  Disable conversion of smileys to emojis.

*-t, --hide-indent*::
  Hide the indentation bar to the left of the reply.

*-n, --nerdfonts*::
  Use Nerd Fonts icons as decorators for some elements (requires a Nerd Font-patched font)

*--force-light-mode, --force-dark-mode*::
  *clx* has a dark color scheme and a light color scheme. The color scheme is automatically chosen based on the color
scheme of the terminal. Use these flags to force a specific color scheme.


*-v, --version*::
  Show the current version of *clx*.

*-q, --debug-mode*::
  Mock all endpoints and use dummy data for the submissions screen and comment section.

== Favorites

Press _f_ to add the currently highlighted submission to your list of favorites. Remove submissions from the Favorites
page with _x_.

Favorites are stored in ~/.config/circumflex/favorites.json. The entries in favorites.json are pretty-printed to make
them both human-readable and VCS-friendly.

== See also

*less*(1), *vim*(1)

== About

Ben Sadeh (github.com/bensadeh/circumflex)

Released under the GNU Affero General Public License v3.0

