= clx(1)
:doctype: manpage
:manmanual: circumflex
:man source: circumflex {release-version}
:revdate: {docdate}

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]


== Name

clx - it's Hacker News in your terminal

== Synopsis

*clx* [_OPTION_]...

== Description

*circumflex* lets you browse Hacker News in your terminal.
Quickly and easily visit the comment section or read the article in Reader Mode.

== Keybindings

_Enter_::
Read the comment section.

_Space_::
Read the article in Reader Mode.

_r_::
Re-fetches submissions for current category.
Purges already fetched submissions from other categories.

_Tab_::
Change category (use Shift + Tab to change in opposite direction).

_o_::
Open link to article in browser.

_c_::
Open comment section in browser.

_f_, _V_::
Add currently highlighted submission to favorites.

_x_::
Remove currently highlighted submission from favorites.

_u_::
Toggle read/unread for the currently highlighted submission.

_g_, _G_::
Go to the top/bottom of the list.

_i_, _?_::
Bring up the help screen.

_q_::
Quit to prompt.

== Navigation

*circumflex* pipes all its content to the pager *less*.
It is recommended to use the following keybindings for moving around:

_j_, _k_::
Scroll up/down one line.

_d_, _u_::
Scroll up/down one half-page.

_h_, _l_::
Hide/unhide all replies.

_n_, _N_::
Scroll between the next/previous _top-level_ comment (comment section) or _headline_ (Reader Mode).

== Commands

*clx add* [_ID_]::
Add item to list of favorites by _ID_.

*clx article* [_ID_]::
Go directly to Reader Mode for a given item _ID_ without first going through the main view.

*clx comments* [_ID_]::
Go directly to the comment section for a given item _ID_ without first going through the main view.

*clx url* [_URL_]::
Open a URL directly in Reader Mode

*clx clear*::
Clear the history of visited __ID__s from ~/.cache/circumflex/history.json.

*clx version*::
Print the version number of *circumflex*.

*clx default-theme*::
Write default theme config to ~/.config/circumflex/theme.toml.

== Options

*-c* _n_, *--comment-width*=_n_::
Set the comment width to _n_ columns.

*-e, --disable-emojis*::
Disable conversion of smileys to emojis.

*-d, --disable-history*::
Disable marking stories as read.

*-n, --nerdfonts*=_true|false_::
Enable or disable Nerd Fonts icons as decorators for some elements (requires a Nerd Font-patched font).
Auto-enabled for Ghostty, which embeds Nerd Fonts. Can also be set with the *NERDFONTS* environment variable.

*-a, --auto-expand*::
Auto expand all replies upon entering the comment section (collapse comments with _h_).

*-v, --version*::
Show the current version of *circumflex*.

*--no-less-verify*::
Do not verify *less* version on startup

*--categories*::
Set the categories in the header. Choose between top, new, best, ask and show.
First category will be treated as the default one. Separate categories with comma.
Default value: "top,best,ask,show"

*--pages*=_n_::
Set the number of pages to fetch per category, between 1 and 5.
Higher values fetch more stories but increase load time.
Only applies to top, new and best. Ask and show always fetch one page because their
story pools are small (~150-200 stories).
Default: 3.

== Favorites

Press _f_ to add the currently highlighted submission to your list of favorites.
Remove submissions from the Favorites page with _x_.

Favorites are stored in ~/.config/circumflex/favorites.json.
The entries in favorites.json are pretty-printed to make them both human-readable and VCS-friendly.

== Environment Variables

*NERDFONTS*::
If this variable is set, *circumflex* will use Nerd Fonts icons as decorators for some elements.
Same as running *clx* with *--nerdfonts*=_true_. Nerd Fonts are also auto-enabled in Ghostty, which embeds Nerd Fonts.

*CLX_BROWSER*::
Set to a custom command to be run when opening links. The URL to the website will be appended to
CLX_BROWSER and ran as a single command.

== See also

*less*(1), *vim*(1)

== About

Ben Sadeh (github.com/bensadeh/circumflex)

Released under the MIT License

