package nerdfonts

const (
	Time                   = ""
	Author                 = ""
	Score                  = "󰜷"
	Comment                = "󰅺"
	CommentDraft           = ""
	CommentPlusOutline     = "󰆃"
	CommentMinusOutline    = "󱗠"
	Search                 = ""
	SearchCommitted        = ""
	SearchResults          = "󱩾"
	CommentSection         = "󰆈"
	CommentSearchCommitted = "󰨼"
	GitHub                 = ""
	Tag                    = ""
	Document               = ""
	Audio                  = ""
	Video                  = ""
	Image                  = "󰋩"
	ImageOff               = "󰠫"
	LinkSelector           = ""
	LinkSelectorOff        = "󰌺"
	YCombinator            = ""
	LeftSeparator          = ""
	RightSeparator         = ""
)
