package theme

import (
	"bytes"
	"fmt"
	"image/color"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"

	"charm.land/lipgloss/v2"
	"github.com/BurntSushi/toml"
)

type Theme struct {
	App      AppColors      `toml:"app"`
	Headline HeadlineColors `toml:"headline"`
	Comment  CommentColors  `toml:"comment"`
	Meta     MetaColors     `toml:"meta"`
	Reader   ReaderColors   `toml:"reader"`
	Header   HeaderColors   `toml:"header"`
	Indent   IndentColors   `toml:"indent"`
}

type AppColors struct {
	Primary   string `toml:"primary"`
	Secondary string `toml:"secondary"`
	Tertiary  string `toml:"tertiary"`
}

type HeadlineColors struct {
	AskHN    string `toml:"ask_hn"`
	ShowHN   string `toml:"show_hn"`
	TellHN   string `toml:"tell_hn"`
	ThankHN  string `toml:"thank_hn"`
	LaunchHN string `toml:"launch_hn"`
	YCLabel  string `toml:"yc_label"`
	Year     string `toml:"year"`
	Audio    string `toml:"audio"`
	Video    string `toml:"video"`
	PDF      string `toml:"pdf"`
}

type CommentColors struct {
	URL          string `toml:"url"`
	Mention      string `toml:"mention"`
	Mod          string `toml:"mod"`
	Variable     string `toml:"variable"`
	Backtick     string `toml:"backtick"`
	OP           string `toml:"op"`
	GP           string `toml:"gp"`
	NewIndicator string `toml:"new_indicator"`
}

type MetaColors struct {
	Author      string `toml:"author"`
	Comments    string `toml:"comments"`
	Score       string `toml:"score"`
	ID          string `toml:"id"`
	NewComments string `toml:"new_comments"`
	URL         string `toml:"url"`
	ReaderMode  string `toml:"reader_mode"`
}

type ReaderColors struct {
	H1    string `toml:"h1"`
	H2    string `toml:"h2"`
	H3    string `toml:"h3"`
	H4    string `toml:"h4"`
	H5    string `toml:"h5"`
	H6    string `toml:"h6"`
	Image string `toml:"image"`
}

type HeaderColors struct {
	C string `toml:"c"`
	L string `toml:"l"`
	X string `toml:"x"`
}

type IndentColors struct {
	Cycle []string `toml:"cycle"`
}

func Default() *Theme {
	return &Theme{
		App: AppColors{
			Primary:   "magenta",
			Secondary: "yellow",
			Tertiary:  "blue",
		},
		Headline: HeadlineColors{
			AskHN:    "blue",
			ShowHN:   "red",
			TellHN:   "magenta",
			ThankHN:  "cyan",
			LaunchHN: "green",
			YCLabel:  "yellow",
			Year:     "magenta",
			Audio:    "cyan",
			Video:    "cyan",
			PDF:      "cyan",
		},
		Comment: CommentColors{
			URL:          "blue",
			Mention:      "yellow",
			Mod:          "green",
			Variable:     "cyan",
			Backtick:     "magenta",
			OP:           "red",
			GP:           "magenta",
			NewIndicator: "cyan",
		},
		Meta: MetaColors{
			Author:      "red",
			Comments:    "magenta",
			Score:       "yellow",
			ID:          "green",
			NewComments: "cyan",
			URL:         "blue",
			ReaderMode:  "green",
		},
		Reader: ReaderColors{
			H1:    "blue",
			H2:    "red",
			H3:    "magenta",
			H4:    "yellow",
			H5:    "green",
			H6:    "white",
			Image: "red",
		},
		Header: HeaderColors{
			C: "magenta",
			L: "yellow",
			X: "blue",
		},
		Indent: IndentColors{
			Cycle: []string{
				"red", "yellow", "green", "cyan", "blue", "magenta",
				"bright_red", "bright_yellow", "bright_green", "bright_cyan", "bright_blue", "bright_magenta",
			},
		},
	}
}

const colorLegend = "# Color values can be:\n" +
	"#   - Named: \"red\", \"blue\", \"green\", \"yellow\", \"magenta\", \"cyan\", \"white\", \"black\"\n" +
	"#   - Bright: \"bright_red\", \"bright_blue\", \"bright_green\", etc.\n" +
	"#   - ANSI 256: \"219\", \"33\", \"196\"\n" +
	"#   - Hex: \"#ff5500\", \"#1a1a2e\"\n\n"

func configHeader() string {
	return "# circumflex theme configuration\n" +
		"#\n" +
		colorLegend
}

func exampleHeader() string {
	return "# circumflex theme configuration\n" +
		"#\n" +
		"# Copy this file to your config directory as theme.toml, or run\n" +
		"# `clx default-theme` to write it there for you.\n" +
		"# Only include the values you want to override — unspecified values\n" +
		"# keep their defaults.\n" +
		"#\n" +
		colorLegend
}

func writeConfig(w io.Writer, header string) error {
	if _, err := io.WriteString(w, header); err != nil {
		return err
	}

	return toml.NewEncoder(w).Encode(Default())
}

// ExampleConfig renders the annotated default theme shipped as
// theme.toml.example; regenerated by share/generate_all.sh.
func ExampleConfig() ([]byte, error) {
	var buf bytes.Buffer
	if err := writeConfig(&buf, exampleHeader()); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func WriteDefaultConfig(path string) error {
	if _, statErr := os.Stat(path); statErr == nil {
		return fmt.Errorf("config already exists at %s", path)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}

	defer func() { _ = f.Close() }()

	return writeConfig(f, configHeader())
}

func Load(path string) (*Theme, error) {
	t := Default()

	if _, statErr := os.Stat(path); os.IsNotExist(statErr) {
		return t, nil
	}

	_, err := toml.DecodeFile(path, t)
	if err != nil {
		return Default(), err
	}

	if bad := t.invalidColors(); len(bad) > 0 {
		return Default(), fmt.Errorf("unrecognized colors in %s: %s", path, strings.Join(bad, ", "))
	}

	return t, nil
}

func (t *Theme) invalidColors() []string {
	var bad []string

	report := func(key, value string) {
		if _, ok := parseColor(value); !ok {
			bad = append(bad, fmt.Sprintf("%s = %q", key, value))
		}
	}

	sections := reflect.ValueOf(t).Elem()
	for i := range sections.NumField() {
		sectionKey := sections.Type().Field(i).Tag.Get("toml")
		section := sections.Field(i)

		for j := range section.NumField() {
			key := sectionKey + "." + section.Type().Field(j).Tag.Get("toml")

			switch value := section.Field(j).Interface().(type) {
			case string:
				report(key, value)
			case []string:
				for _, s := range value {
					report(key, s)
				}
			}
		}
	}

	return bad
}

var namedColors = map[string]color.Color{
	"red":            lipgloss.Red,
	"blue":           lipgloss.Blue,
	"green":          lipgloss.Green,
	"yellow":         lipgloss.Yellow,
	"magenta":        lipgloss.Magenta,
	"cyan":           lipgloss.Cyan,
	"white":          lipgloss.White,
	"black":          lipgloss.Black,
	"bright_red":     lipgloss.BrightRed,
	"bright_blue":    lipgloss.BrightBlue,
	"bright_green":   lipgloss.BrightGreen,
	"bright_yellow":  lipgloss.BrightYellow,
	"bright_cyan":    lipgloss.BrightCyan,
	"bright_magenta": lipgloss.BrightMagenta,
	"bright_white":   lipgloss.BrightWhite,
	"bright_black":   lipgloss.BrightBlack,
}

func ParseColor(s string) color.Color {
	c, _ := parseColor(s)

	return c
}

func parseColor(s string) (color.Color, bool) {
	s = strings.TrimSpace(s)

	// An empty value is an explicit request for the terminal's default color.
	if s == "" {
		return lipgloss.NoColor{}, true
	}

	if c, ok := namedColors[s]; ok {
		return c, true
	}

	if strings.HasPrefix(s, "#") {
		c := lipgloss.Color(s)
		_, invalid := c.(lipgloss.NoColor)

		return c, !invalid
	}

	if n, err := strconv.Atoi(s); err == nil && n >= 0 && n <= 255 {
		return lipgloss.ANSIColor(n), true
	}

	return lipgloss.NoColor{}, false
}
