package list

import (
	"clx/style"
	"time"

	"charm.land/bubbles/v2/spinner"
	"charm.land/lipgloss/v2"
	"charm.land/lipgloss/v2/compat"
)

const (
	bullet               = "•"
	ellipsis             = "…"
	spinnerFrameDuration = 900 * time.Millisecond
)

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	TitleBar lipgloss.Style
	Spinner  lipgloss.Style

	StatusBar   lipgloss.Style
	StatusEmpty lipgloss.Style

	NoItems lipgloss.Style

	PaginationStyle lipgloss.Style
	HelpStyle       lipgloss.Style

	// Styled characters.
	ActivePaginationDot   lipgloss.Style
	InactivePaginationDot lipgloss.Style
	ArabicPagination      lipgloss.Style
	DividerDot            lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this list
// component.
func DefaultStyles() (s Styles) {
	s.TitleBar = lipgloss.NewStyle().Padding(0, 0, 1, 2)

	s.Spinner = lipgloss.NewStyle()

	s.StatusEmpty = lipgloss.NewStyle()

	s.NoItems = lipgloss.NewStyle().
		Foreground(compat.AdaptiveColor{Light: lipgloss.Color("#909090"), Dark: lipgloss.Color("#626262")})

	s.ArabicPagination = lipgloss.NewStyle()

	s.PaginationStyle = lipgloss.NewStyle().PaddingLeft(2)

	s.HelpStyle = lipgloss.NewStyle().Padding(1, 0, 0, 2)

	s.ActivePaginationDot = lipgloss.NewStyle().
		SetString(bullet)

	s.InactivePaginationDot = lipgloss.NewStyle().
		Faint(true).
		SetString(bullet)

	s.DividerDot = lipgloss.NewStyle().
		Faint(true).
		SetString(" " + bullet + " ")

	return s
}

func getSpinner() spinner.Spinner {
	normal := lipgloss.NewStyle()

	color := lipgloss.NewStyle()

	magenta := style.HeaderC()
	yellow := style.HeaderL()
	blue := style.HeaderX()

	return spinner.Spinner{
		Frames: []string{
			normal.Render("fetching") + color.Foreground(magenta).Render(".") + color.Foreground(yellow).Render(".") + color.Foreground(blue).Render("."),
			normal.Render("fetching   "),
			normal.Render("fetching") + color.Foreground(magenta).Render(".") + normal.Render("  "),
			normal.Render("fetching") + color.Foreground(magenta).Render(".") + color.Foreground(yellow).Render(".") + normal.Render(" "),
		},
		FPS: spinnerFrameDuration,
	}
}
