.nh
.TH "clx" "1" "Oct 2021" "Ben Sadeh" "circumflex"

.SH NAME
.PP
clx\-add \- Add item to list of favorites by ID


.SH SYNOPSIS
.PP
\fBclx add\fP


.SH DESCRIPTION
.PP
Add item to list of favorites by ID. Enter the comment section from inside 'clx' to update fields.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for add


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-c\fP, \fB\-\-comment\-width\fP=65
	set the comment width

.PP
\fB\-d\fP, \fB\-\-disable\-history\fP[=false]
	disable marking stories as read

.PP
\fB\-t\fP, \fB\-\-hide\-indent\fP[=false]
	hide the indentation symbol

.PP
\fB\-i\fP, \fB\-\-indent\-size\fP=2
	set the indent size

.PP
\fB\-n\fP, \fB\-\-orange\-header\fP[=false]
	set the header to black on orange

.PP
\fB\-o\fP, \fB\-\-plain\-comments\fP[=false]
	disable syntax highlighting for comments

.PP
\fB\-p\fP, \fB\-\-plain\-headlines\fP[=false]
	disable syntax highlighting for headlines

.PP
\fB\-m\fP, \fB\-\-preserve\-right\-margin\fP[=false]
	preserve right margin at the cost of comment width

.PP
\fB\-r\fP, \fB\-\-relative\-numbering\fP[=false]
	use relative numbering for submissions

.PP
\fB\-j\fP, \fB\-\-show\-jobs\fP[=false]
	show submissions of the type 'X is hiring'

.PP
\fB\-s\fP, \fB\-\-smiley\-emojis\fP[=false]
	convert smileys to emojis

.PP
\fB\-a\fP, \fB\-\-use\-alt\-indent\-block\fP[=false]
	use alternate indentation block


.SH SEE ALSO
.PP
\fBclx(1)\fP
