'\" t
.\"     Title: clx
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-05-05
.\"    Manual: circumflex
.\"    Source: circumflex 2.9
.\"  Language: English
.\"
.TH "CLX" "1" "2023-05-05" "circumflex 2.9" "circumflex"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
clx \- it\*(Aqs Hacker News in your terminal
.SH "SYNOPSIS"
.sp
\fBclx\fP [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
\fBcircumflex\fP lets you browse Hacker News in your terminal.
Quickly and easily visit the comment section or read the article in Reader Mode.
.SH "KEYBINDINGS"
.sp
\fIEnter\fP
.RS 4
Read the comment section.
.RE
.sp
\fISpace\fP
.RS 4
Read the article in Reader Mode.
.RE
.sp
\fIr\fP
.RS 4
Re\-fetches submissions for current category.
Purges already fetched submissions from other categories.
.RE
.sp
\fITab\fP
.RS 4
Change category (use Shift + Tab to change in opposite direction).
.RE
.sp
\fIo\fP
.RS 4
Open link to article in browser.
.RE
.sp
\fIc\fP
.RS 4
Open comment section in browser.
.RE
.sp
\fIf\fP
.RS 4
Add currently highlighted submission to favorites.
.RE
.sp
\fIx\fP
.RS 4
Remove currently highlighted submission from favorites.
.RE
.sp
\fIq\fP
.RS 4
Quit to prompt.
.RE
.SH "NAVIGATION"
.sp
\fBcircumflex\fP pipes all its content to the pager \fBless\fP.
It is recommended to use the following keybindings for moving around:
.sp
\fIj\fP, \fIk\fP
.RS 4
Scroll up/down one line.
.RE
.sp
\fId\fP, \fIu\fP
.RS 4
Scroll up/down one half\-page.
.RE
.sp
\fIh\fP, \fIl\fP
.RS 4
Hide/unhide all replies.
.RE
.sp
\fIn\fP, \fIN\fP
.RS 4
Scroll between the next/previous \fItop\-level\fP comment (comment section) or \fIheadline\fP (Reader Mode).
.RE
.SH "COMMANDS"
.sp
\fBclx add\fP [\fIID\fP]
.RS 4
Add item to list of favorites by \fIID\fP.
.RE
.sp
\fBclx read\fP [\fIID\fP]
.RS 4
Go directly to Reader Mode for a given item \fIID\fP without first going through the main view.
.RE
.sp
\fBclx view\fP [\fIID\fP]
.RS 4
Go directly to the comment section for a given item \fIID\fP without first going through the main view.
.RE
.sp
\fBclx clear\fP
.RS 4
Clear the history of visited \fIID\fPs from ~/.cache/circumflex/history.json.
.RE
.SH "OPTIONS"
.sp
\fB\-c\fP \fIn\fP, \fB\-\-comment\-width\fP=\fIn\fP
.RS 4
Set the comment width to \fIn\fP columns.
.RE
.sp
\fB\-p, \-\-plain\-headlines\fP
.RS 4
Disable syntax highlighting for headlines.
.RE
.sp
\fB\-o, \-\-plain\-comments\fP
.RS 4
Disable syntax highlighting for comments.
.RE
.sp
\fB\-e, \-\-disable\-emojis\fP
.RS 4
Disable conversion of smileys to emojis.
.RE
.sp
\fB\-d, \-\-disable\-history\fP
.RS 4
Disable marking submissions as read.
.RE
.sp
\fB\-t, \-\-hide\-indent\fP
.RS 4
Hide the indentation bar to the left of the reply.
.RE
.sp
\fB\-n, \-\-nerdfonts\fP
.RS 4
Use Nerd Fonts icons as decorators for some elements (requires a Nerd Font\-patched font).
.RE
.sp
\fB\-a, \-\-auto\-expand\fP
.RS 4
Auto expand all replies upon entering the comment section (collapse comments with \fIh\fP).
.RE
.sp
\fB\-v, \-\-version\fP
.RS 4
Show the current version of \fBcircumflex\fP.
.RE
.sp
\fB\-q, \-\-debug\-mode\fP
.RS 4
Mock all endpoints and use dummy data for the submissions screen and comment section.
.RE
.sp
\fB\-\-no\-less\-verify\fP
.RS 4
Do not verify \fBless\fP version on startup
.RE
.SH "FAVORITES"
.sp
Press \fIf\fP to add the currently highlighted submission to your list of favorites.
Remove submissions from the Favorites page with \fIx\fP.
.sp
Favorites are stored in ~/.config/circumflex/favorites.json.
The entries in favorites.json are pretty\-printed to make them both human\-readable and VCS\-friendly.
.SH "SEE ALSO"
.sp
\fBless\fP(1), \fBvim\fP(1)
.SH "ABOUT"
.sp
Ben Sadeh (github.com/bensadeh/circumflex)
.sp
Released under the GNU Affero General Public License v3.0