name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v7

      - name: Check formatting
        run: golangci-lint fmt --diff ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...